#!/bin/sh /etc/rc.common
# Copyright (C) 2006 OpenWrt.org

START=99
start() {
	/usr/sbin/ledctrl power off
	# Run leds_monitor
	/usr/sbin/leds_monitor /dev/input/event0&
	# Sensor monitor
	/usr/sbin/sensors_monitor&
	# Wan monitor 
	/usr/sbin/wan_monitor&
	# performance tuning
	echo 1 > /proc/irq/26/smp_affinity
	echo 2 > /proc/irq/25/smp_affinity
	# eth0
	echo 2 > /sys/class/net/eth0/queues/rx-0/rps_cpus
	echo 2 > /sys/class/net/eth0/queues/rx-1/rps_cpus
	echo 2 > /sys/class/net/eth0/queues/rx-2/rps_cpus
	echo 2 > /sys/class/net/eth0/queues/rx-3/rps_cpus
	echo 2 > /sys/class/net/eth0/queues/rx-4/rps_cpus
	echo 2 > /sys/class/net/eth0/queues/rx-5/rps_cpus
	echo 2 > /sys/class/net/eth0/queues/rx-6/rps_cpus
	echo 2 > /sys/class/net/eth0/queues/rx-7/rps_cpus
	 
	# eth1
	echo 1 > /sys/class/net/eth1/queues/rx-0/rps_cpus
	echo 1 > /sys/class/net/eth1/queues/rx-1/rps_cpus
	echo 1 > /sys/class/net/eth1/queues/rx-2/rps_cpus
	echo 1 > /sys/class/net/eth1/queues/rx-3/rps_cpus
	echo 1 > /sys/class/net/eth1/queues/rx-4/rps_cpus
	echo 1 > /sys/class/net/eth1/queues/rx-5/rps_cpus
	echo 1 > /sys/class/net/eth1/queues/rx-6/rps_cpus
	echo 1 > /sys/class/net/eth1/queues/rx-7/rps_cpus

	# wait for all wifi configuration done
	sleep 20
	# enable wifi scanning for wdev0ap0
	iwpriv wdev0sta0 stamode 7
	iwconfig wdev0sta0 commit
	iwpriv wdev0sta0 stascan 1

	# enable wifi scanning for wdev1ap0
	iwpriv wdev1sta0 stamode 8
	iwconfig wdev1sta0 commit
	iwpriv wdev1sta0 stascan 1
}
